### PR TITLE
Added elements and changed SOCIALBLADE reference

### PR DESCRIPTION
**Pull request by xl400v**
Added items live chat (R88-R93):
- [x] new_sponsor
- [x] simple_text
- [x] sticker
- [x] donat

### CODE REVIEW

**Review by zerodytrash — CHANGES_REQUESTED** [review]
Hi,

Thank you for your contribution!
What exactly is the reason why you removed socialblade? I have looked at playboard but I get this error message on almost all channels. Looks like socialblade has much more channels in the database. I would suggest to integrate both options. Socialbalde and Playboard. What do you think of this?

image

**Comment by xl400v** [comment]
The `Socialblade` collects many times more info, but only for channels with than 1000 subscribers and more.
I find the `PlayBoard` useless. It's up to you wish, of course ;)

**Comment by zerodytrash** [comment]
ok please reinstate Socialblade, so that we have `Socialblade` and `PlayBoard`. Everything else looks good. I will merge it then.

**Review by zerodytrash — APPROVED** [review]
Thanks, and sorry for the delay.

**Pull request merged**
